# docker-compose.ci.yml
services:
  islands_engine:
    # Build the application in-place using Dockerfile
    build: .
    container_name: islands_engine
    # Ensure that if everything went fine, our app closes with exit code 0
    environment:
      - CI_MODE=true
